import "../css/app.css";
import "./menu-toggler";
import "./modal";
import "./ancor-link-smooth";
import "./caraousel";
import "./accordion";
import "./slider";
import "./shopping-cart";
import "./shippingDetail";
